Avoid calling closed? outside of synchronize block
capistrano/sshkit pull request #534
Opened 2024-04-04 07:13 UTC by djmb

`closed?` calls `process` on the connection which is not safe because we have not synchronised the connection pool. Another thread might concurrently checkout the connection and start sending commands as well.

2024-04-04 07:24 UTC, djmb commented
When using SSHKit with a 100+ hosts, we sometimes get IOErrors like this:

```
[ERROR (IOError): Exception while executing on host foo: closed stream]
```

Debugging showed that a packet was being sent to the remove server twice, which was causing it to close the connection. This was caused by two threads using the connection concurrently, the eviction thread and on of the SSHKit parallel runner threads. 

The duplicate packets came from [here](https://github.com/net-ssh/net-ssh/blob/eb2a49db51e33829e102e8c651e8ae0edc3ad3b7/lib/net/ssh/buffered_io.rb#L99-L108) in net-ssh, where both threads call `send` before either calls `output.consume!`.

Looking at the eviction code, the call to `closed?(first_conn)` outside the synchronize block looked suspicious as it calls `conn.process(0)` which will send a test packet.

The check looks like a performance optimisation, so I think it should be safe to remove. We've not seen the errors again with this fix running.

2024-04-12 01:00 UTC, mattbrictson requested changes
Thanks for the fix! Could you make the following change to address the rubocop failure in CI?

2024-04-15 15:12 UTC, djmb commented
Thanks for the review @mattbrictson - I've committed your suggestion.

2024-04-15 17:03 UTC, mattbrictson approved these changes

2024-04-15 17:03 UTC, merged